### ISSUE TITLE
Use WSGI (or maybe ASGI)?

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller#135]
We currently run the sdx-controller app with `python3 -m swagger_server`, which works fine during development, but there is also a startup message that reminds us to use a WSGI server:

```
INFO:werkzeug:WARNING: This is a development server.
Do not use it in a production deployment. 
Use a production WSGI server instead.
```

[Flask's documentation](https://flask.palletsprojects.com/en/2.3.x/tutorial/deploy/) also recommends using WSGI server for production deployments:

> When running publicly rather than in development, you should not use the built-in development server (flask run). The development server is provided by Werkzeug for convenience, but is not designed to be particularly efficient, stable, or secure.
>
> Instead, use a production WSGI server.

**Comment by YufengXin** [comment]
Yes, that's the way to go, but we'll address this when we get closer to production stage.

**Comment by sajith** [comment]
@YufengXin I'm just capturing this for now, before I forget.  Not actually going to do this right now. :-)
