### ISSUE TITLE
Breakdown investigation

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller#145]
Counterpart of https://github.com/atlanticwave-sdx/pce/issues/112.  Given three topologies ([amlight](https://github.com/atlanticwave-sdx/sdx-controller/blob/main/samples/topologies/amlight.json), [sax](https://github.com/atlanticwave-sdx/sdx-controller/blob/main/samples/topologies/sax.json), [zaoxi](https://github.com/atlanticwave-sdx/sdx-controller/blob/main/samples/topologies/zaoxi.json)), and a connection request like (which probably is incorrect?) to `POST /connection`:

```json
{
    "id": "a6228238-3d47-4bf7-af56-141ec6e899f8",
    "name": "sax-a1-to-sax-b1",
    "start_time": "2000-01-23T04:56:07.000Z",
    "end_time": "2000-01-23T04:56:07.000Z",
    "bandwidth_required": 10,
    "latency_required": 300,
    "egress_port":
    {
        "id": "urn:ogf:network:sdx:port:sax:A1:1",
        "name": "Novi100:1",
        "node": "urn:ogf:network:sdx:node:sax:A1",
        "status": "up"
    },
    "ingress_port":
    {
        "id": "urn:ogf:network:sdx:port:sax:B1:2",
        "name": "Unknown",
        "node": "urn:ogf:network:sdx:node:sax:B1",
        "status": "up"
    }
}
```

We get a breakdown like:

```json
{
    "urn:ogf:network:sdx": {
        "ingress_port": {
            "id": "urn:ogf:network:sdx:port:sax:B1:2",
            "name": "Unknown",
            "short_name": null,
            "node": "urn:ogf:network:sdx:node:sax:B1",
            "label_range": null,
            "status": null,
            "state": null,
            "private_attributes": null
        },
        "egress_port": {
            "id": "urn:ogf:network:sdx:port:sax:B1:3",
            "name": "Novi01:3",
            "node": "urn:ogf:network:sdx:node:sax:B1",
            "short_name": "B1:3",
            "label_range": [
                "100-200",
                "10001"
            ],
            "status": "up"
        }
    }
}
```

(Details are probably incorrect; will update.)

The `"urn:ogf:network:sdx"` key in the response probably should be `"urn:ogf:network:sdx:topology:sax.net"`.  Because it is the former, the domain can't be correctly determined.

**Comment by YufengXin** [comment]
As a reference, I have a copy of the pre-refactoring PCE and Datamodel in my laptop (you need to pip install the two packages first). So I retried the unittest: tests.test_Solver, that tests the 3-domain connection. 
One useful debugging out is this line:
----
Request Connectivity: 5, 2 = 1
-------

the code basically check on if there at least exists a path for the request, before doing the TE computation. 

Its full breakdown output is as follows:
---------------
python -m unittest -v tests.test_Solver 
---------------------
test_computation_breakdown (tests.test_Solver.Test_Solver) ... Adding Topology:./tests/data/amlight.json
Warning: no interdomain links detected!
Adding Topology:./tests/data/zaoxi.json
Warning: no interdomain links detected!
Adding Topology:./tests/data/sax.json
Request Connectivity: 9, 2 = 1
Graph connectivity:True
Topology Generated!
Number of variables = 28
Number of constraints = 39
Objective value = 24348015.0

[{'1': [[9, 7], [7, 5], [5, 3], [3, 0], [0, 2]]}, 24348015.0]
domain breakdown:
{'urn:ogf:network:sdx:topology:zaoxi.net': [[9, 7], [7, 5]], 'urn:ogf:network:sdx:topology:sax.net': [[5, 3], [3, 0]], 'urn:ogf:network:sdx:topology:amlight.net': [[0, 2]]}
{'urn:ogf:network:sdx:topology:zaoxi.net': {'ingress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:A1:2', 'name': 'Novi100:2', 'short_name': None, 'node': 'urn:ogf:network:sdx:node:zaoxi:A1', 'label_range': None, 'status': None, 'state': None, 'private_attributes': None}, 'egress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:B1:1', 'name': 'Novi01:1', 'node': 'urn:ogf:network:sdx:node:zaoxi:B1', 'short_name': 'B1:1', 'label_range': ['100-200', '10001'], 'status': 'up'}}, 'urn:ogf:network:sdx:topology:sax.net': {'ingress_port': {'id': 'urn:ogf:network:sdx:port:sax:B3:1', 'label_range': ['100-200', '1000'], 'name': 'Novi02:3', 'node': 'urn:ogf:network:sdx:node:sax:B3', 'short_name': 'B3:1', 'status': 'up'}, 'egress_port': {'id': 'urn:ogf:network:sdx:port:sax:B1:1', 'name': 'Novi01:1', 'node': 'urn:ogf:network:sdx:node:sax:B1', 'short_name': 'B1:1', 'label_range': ['100-200', '10001'], 'status': 'up'}}, 'urn:ogf:network:sdx:topology:amlight.net': {'ingress_port': {'id': 'urn:sdx:port:amlight:B1:1', 'name': 'Novi01:1', 'node': 'urn:sdx:node:amlight.net:B1', 'short_name': 'B1:1', 'label_range': ['100-200', '10001'], 'status': 'up'}, 'egress_port': {'id': 'urn:sdx:port:amlight.net:A1:1', 'name': 'Novi100:1', 'short_name': None, 'node': 'urn:sdx:node:amlight.net:A1', 'label_range': None, 'status': None, 'state': None, 'private_attributes': None}}}
-----------------------

**Comment by sajith** [comment]
The way I understand this, pce can still solve the "original" sample request and the "merged" topology, but it will fail to resolve a node's domain.

```console
$ tox -- -s tests/test_Solver.py::SolverTests::test_computation_breakdown
[..]
TEManager: connection_data: {'id': 'id', 'name': 'AMLight', 'start_time': '2000-01-23T04:56:07.000Z', 'end_time': '2000-01-23T04:56:07.000Z', 'bandwidth_required': 10, 'latency_required': 300, 'egress_port': {'id': 'urn:sdx:port:amlight.net:A1:1', 'name': 'Novi100:1', 'node': 'urn:sdx:node:amlight.net:A1', 'status': 'up'}, 'ingress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:A1:2', 'name': 'Novi100:2', 'node': 'urn:ogf:network:sdx:node:zaoxi:A1', 'status': 'up'}}
TEManager: self.connection: {'egress_port': {'id': 'urn:sdx:port:amlight.net:A1:1',
                 'label_range': None,
                 'name': 'Novi100:1',
                 'node': 'urn:sdx:node:amlight.net:A1',
                 'private_attributes': None,
                 'short_name': None,
                 'state': None,
                 'status': None},
 'end_time': '2000-01-23T04:56:07.000Z',
 'id': 'id',
 'ingress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:A1:2',
                  'label_range': None,
                  'name': 'Novi100:2',
                  'node': 'urn:ogf:network:sdx:node:zaoxi:A1',
                  'private_attributes': None,
                  'short_name': None,
                  'state': None,
                  'status': None},
 'name': 'AMLight',
 'quantity': None,
 'start_time': '2000-01-23T04:56:07.000Z',
 'status': None}
generate_connection_te(), ports: ingress_port.id: urn:ogf:network:sdx:port:zaoxi:A1:2, egress_port.id: urn:sdx:port:amlight.net:A1:1
Setting required_latency: 300, required_bandwidth: 10
Number of nodes: 10
Graph edges: [(0, 1), (0, 2), (0, 3), (1, 2), (1, 4), (3, 4), (3, 5), (3, 6), (4, 5), (4, 6), (5, 7), (7, 8), (7, 9), (8, 9)]
Traffic Matrix: TrafficMatrix(connection_requests=[ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)])
Creating data model: #nodes: 10, #links: 14
request: 1
links: 28
bound 1: 10
bound 2: 38
bound 3: 39
r=1:m=10:n=28
out: (10, 28)

Constraints Shape:10:28
np:(10, 28) : (28, 28)
flow_lhs: (38, 28)
latcons: (1, 28)
Objecive: Cost
cost len: 28
lhs shape: (39, 28)
rhs shape: 39
Number of variables = 28
num_constraints: 39
num_inequality: 29
39
39
29
Number of constraints = 39
Objective value = 5.0
(1, 28)
Adding edge (9, 7) for request ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)
Adding edge (7, 5) for request ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)
Adding edge (5, 3) for request ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)
Adding edge (3, 0) for request ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)
Adding edge (0, 2) for request ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300)
solution_translator result: ConnectionSolution(connection_map={ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300): [ConnectionPath(source=9, destination=7), ConnectionPath(source=7, destination=5), ConnectionPath(source=5, destination=3), ConnectionPath(source=3, destination=0), ConnectionPath(source=0, destination=2)]}, cost=5.0)
TESolver result: ConnectionSolution(connection_map={ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300): [ConnectionPath(source=9, destination=7), ConnectionPath(source=7, destination=5), ConnectionPath(source=5, destination=3), ConnectionPath(source=3, destination=0), ConnectionPath(source=0, destination=2)]}, cost=5.0)
domain: ConnectionRequest(source=9, destination=2, required_bandwidth=10, required_latency=300), links: [ConnectionPath(source=9, destination=7), ConnectionPath(source=7, destination=5), ConnectionPath(source=5, destination=3), ConnectionPath(source=3, destination=0), ConnectionPath(source=0, destination=2)]
count: 0, link: ConnectionPath(source=9, destination=7)
source node: {'id': 'urn:ogf:network:sdx:node:zaoxi:A1'}, destination node: {'id': 'urn:ogf:network:sdx:node:zaoxi:B1'}
source domain: urn:ogf:network:sdx, destination domain: urn:ogf:network:sdx
count: 1, link: ConnectionPath(source=7, destination=5)
source node: {'id': 'urn:ogf:network:sdx:node:zaoxi:B1'}, destination node: {'id': 'urn:ogf:network:sdx:node:sax:B3'}
source domain: urn:ogf:network:sdx, destination domain: urn:ogf:network:sdx
count: 2, link: ConnectionPath(source=5, destination=3)
source node: {'id': 'urn:ogf:network:sdx:node:sax:B3'}, destination node: {'id': 'urn:ogf:network:sdx:node:sax:B1'}
source domain: urn:ogf:network:sdx, destination domain: urn:ogf:network:sdx
count: 3, link: ConnectionPath(source=3, destination=0)
source node: {'id': 'urn:ogf:network:sdx:node:sax:B1'}, destination node: {'id': 'urn:sdx:node:amlight.net:B1'}
source domain: urn:ogf:network:sdx, destination domain: urn:ogf:network:sdx
count: 4, link: ConnectionPath(source=0, destination=2)
source node: {'id': 'urn:sdx:node:amlight.net:B1'}, destination node: {'id': 'urn:sdx:node:amlight.net:A1'}
source domain: urn:ogf:network:sdx, destination domain: urn:ogf:network:sdx
[intermediate] breakdown: {'urn:ogf:network:sdx': [ConnectionPath(source=9, destination=7), ConnectionPath(source=7, destination=5), ConnectionPath(source=5, destination=3), ConnectionPath(source=3, destination=0), ConnectionPath(source=0, destination=2)]}
Creating domain_breakdown: domain: urn:ogf:network:sdx, links: [ConnectionPath(source=9, destination=7), ConnectionPath(source=7, destination=5), ConnectionPath(source=5, destination=3), ConnectionPath(source=3, destination=0), ConnectionPath(source=0, destination=2)]
generate_connection_breakdown(): domain_breakdown: {'urn:ogf:network:sdx': {'ingress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:A1:2', 'name': 'Novi100:2', 'short_name': None, 'node': 'urn:ogf:network:sdx:node:zaoxi:A1', 'label_range': None, 'status': None, 'state': None, 'private_attributes': None}, 'egress_port': {'id': 'urn:sdx:port:amlight.net:B1:3', 'name': 'Novi01:3', 'node': 'urn:sdx:node:amlight.net:B1', 'short_name': 'B1:3', 'label_range': ['100-200', '10001'], 'status': 'up'}}}
Breakdown: {'urn:ogf:network:sdx': {'ingress_port': {'id': 'urn:ogf:network:sdx:port:zaoxi:A1:2', 'name': 'Novi100:2', 'short_name': None, 'node': 'urn:ogf:network:sdx:node:zaoxi:A1', 'label_range': None, 'status': None, 'state': None, 'private_attributes': None}, 'egress_port': {'id': 'urn:sdx:port:amlight.net:B1:3', 'name': 'Novi01:3', 'node': 'urn:sdx:node:amlight.net:B1', 'short_name': 'B1:3', 'label_range': ['100-200', '10001'], 'status': 'up'}}}
```

So it looks like a regression was introduced (exactly when that happened is unclear), and regressions happen because of the lack of a clear mental model.  The first order of business should be getting the ideas straight.  So it would be good (for me!) to have a few things clarified and documented, and write some more tests (and/or update the existing tests) so that we can catch any future regressions:

1. What does a "merged" topology do?  Why do we use it, instead of dynamically recomputing the graph when a connection request comes in?
2. What should `add_topology()` and `update_topology()` do, and what they should not do?  What properties do we expect TEManager to maintain when a topology is added/updated/removed?
3. What are the various topology files we have (sdx.json, sax.json, amlight.json, zaoxi.json), and when should we use them?  What is the "canonical" version of these files?  (We have diverging copies in this repo and in pce.)
4. What is the right behavior for `TopologyManager.get_domain()`, and how do we get that behavior?

**Comment by YufengXin** [comment]
This is better than the demo that Cong did during the all-hands meeting, as I remembered
1. when Cong did the demo, it appeared that the multi-domain request failed due to PCE "could not find an optimal solution"? 
2. In the same domain, when he tried the connection within one domain, the breakdown worked as the sdx-lc received the message.

The three json files meant to emulate the topologies from the three domain. Let's first make them consistent between the pce and sdx-controller.

The update_topology() meant to handle the case the topology from a domain is updated via sdx-lc.

**Comment by sajith** [comment]
I am going to test this some more in https://github.com/atlanticwave-sdx/pce/pull/115.

It appears to me that the original request could be solved when TEManager has just the "merged" topology, but it will fail to resolve domains correctly.  Things go haywire when we add more topologies to TEManager such that the same request will fail to find a solution.

I could be wrong. Let me find out. :-)

**Comment by sajith** [comment]
I think I've found the problem, or at least one problem.  In the scenario that I thought was broken, I (probably) was asking for bandwidth and latency that were impossible to satisfy, given the constraints.  

The [test_request.json](https://github.com/atlanticwave-sdx/sdx-controller/blob/main/tests/data/test_request.json) in this repo and the [test_request.json](https://github.com/atlanticwave-sdx/pce/blob/main/tests/data/test_request.json) in pce differ, and the crucial difference is here:

```
-    "bandwidth_required": 100,
-    "latency_required": 20,
+    "bandwidth_required": 10,
+    "latency_required": 300,
```

Solver seems to be able to satisfy the request with lower bandwidth and higher latency, regardless of how we set up TEManager: with a "merged" topology, or without.  Except that, with the "merged" topology, domain names would be resolved incorrectly.

(Aside: I am not sure what the units of bandwidth and latency are here... and the meaning of `latency_required`.  Perhaps we can name things appropriately to `latency_maximum` or some such?, and spell out the units?)

**Comment by YufengXin** [comment]
Every link In the topology has the capacity constraints in bw and latency profile. And the PCE tries to find the optimal solution within these constraints. The units are default, in the specification, 10mbps for the bw and ms for the latency, (so we don't need to parse different units.)

**Comment by sajith** [comment]
It probably is better to parse them, perhaps using [humanfriendly](https://pypi.org/project/humanfriendly/) or similar library? 

```python
>>> from humanfriendly import parse_size, parse_timespan
>>> parse_size("10 MB")
10000000
>>> parse_size("10MB")
10000000
>>> parse_size("10 MiB")
10485760
>>> parse_timespan("1h")
3600.0
>>> parse_timespan("1ms")
0.001
>>> parse_timespan("1us")
1e-06
```

Less room for confusion that way, and we won't have to refer to the spec for these things.  But then we will be introducing a new dependency, so it is a trade-off. :-)
