### ISSUE TITLE
Upgrade MongoDB

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller#158]
`docker compose up` prints, among other things, a warning that "NOTE: This is a development version (3.7.9) of MongoDB...  Not recommended for production":

```
mongodb         | 2023-05-19T18:42:12.241+0000 I CONTROL  [initandlisten]
mongodb         | 2023-05-19T18:42:12.241+0000 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.7.9) of MongoDB.
mongodb         | 2023-05-19T18:42:12.241+0000 I CONTROL  [initandlisten] **       Not recommended for production.
mongodb         | 2023-05-19T18:42:12.241+0000 I CONTROL  [initandlisten]
```

**Comment by mcevik0** [comment]
Kytos database backend use mongodb 5.0
-https://github.com/atlanticwave-sdx/sdx-continuous-development/blob/5e6715dff85db9fa11a97aa2b88603ecc3250e74/data-plane/os_base/mongo_base/Dockerfile#L1

- https://github.com/atlanticwave-sdx/sdx-deployment/blob/a8894b24dec722709c048ecfe7c5e2871a0d1220/awsdx-ansible/roles/awsdx/vars/renci.yml#L120

**Comment by sajith** [comment]
From some quick tests it looks like we'll be able to switch to MongoDB 4.2 (no migration required), or MongoDB 5.0 (there's incompatibility in on-disk data so we will likely have to throw away the existing data, which is not a big deal right now).  The app starts up fine.  I don't know what new problems will be introduced though. :-)

@congwang09 Mentioned troubles with switching to a newer MongoDB. I don't have the details.  Perhaps we can look into this after the upcoming release.  For now I just wanted to make a note of this.
