### ISSUE TITLE
Failure handling when a link is down.

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/sdx-controller#161]
As a basic restoration mechanism, when a (inter-domain) link in the topology is reported down, the SDX-controller should collect all the connections using the failed link and recall the PCE solver to compute the new path for these connections.

1. When new connection request is first provisioned, with the breakdown information, the controller should build a <link, connections> map.
2. A link breakdown even should come from sdx-LC (from domain), for testing purpose, emulate/enable this at the sdx-LC.
3. After receiving the message, the sdx-controller should trigger the failure-handling function:
3.1 identify the broken connections
3.2 Tear down these connections (calling the sdx-LC)
3.3 Update the topology by removing the broken link
3.4 Call PCE function to recalculate the connections and generate the new breakdowns 
3.5.Re-establish the connections by sending the breakdowns to LCs.

**Comment by italovalcy** [comment]
Currently the SDX-Controller is leveraging the `link_failure` message type coming from SDX-LC, instead of actually processing the topology to derivate situations of Link failures.
