### ISSUE TITLE
connection handler is sending the breakdown twice for the SDX LC 

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-controller#230]
Hi,

I believe this error was introduced by PR #226 , which ended up sending the breakdown connections twice for the SDX LC:

https://github.com/atlanticwave-sdx/sdx-controller/blob/main/sdx_controller/handlers/connection_handler.py#L159-L160

**Comment by YufengXin** [comment]
@congwang09 would you please take a look on this and #229 when you get a chance. 
That PR for refactoring probably created the bug.
