### ISSUE TITLE
DELETE /connection endpoint only returns success message but does not delete circuit

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-controller#266]
The endpoint returns an ok message but the circuit does not get deleted from the database

**Comment by usmanazFIU** [comment]
@congwang09 i tried deleting connection again. it says deleted but connection is still appearing in the GET list connections endpoint

**Comment by usmanazFIU** [comment]
<img width="862" alt="image" src="https://github.com/atlanticwave-sdx/sdx-controller/assets/104851066/0ab25d58-3a21-418b-8a14-7d68f4db5335">
i deleted the id 35da7792-6038-4cef-a3ba-862a678053da

**Comment by usmanazFIU** [comment]
<img width="716" alt="image" src="https://github.com/atlanticwave-sdx/sdx-controller/assets/104851066/b46e700a-dbcc-404a-acea-96ba2d46f94a">

**Comment by congwang09** [comment]
@usmanazFIU Are you running the latest code?
The behavior should be like this:
Send connection request, return 200.
Then delete the connection, return 200.
If delete connection again for same connection, return 404 not found.
If query the connection again this time, will return 404 not found.

```
sdx-controller-sdx-controller-1  | INFO:     104.59.236.164:62063 - "POST /SDX-Controller/1.0.0/connection HTTP/1.1" 200 OK
sdx-controller-sdx-controller-1  | INFO:     104.59.236.164:62065 - "DELETE /SDX-Controller/1.0.0/connection/285eea4b-1e86-4d54-bd75-f14b8cb4a63a HTTP/1.1" 200 OK
sdx-controller-sdx-controller-1  | INFO:     104.59.236.164:62066 - "DELETE /SDX-Controller/1.0.0/connection/285eea4b-1e86-4d54-bd75-f14b8cb4a63a HTTP/1.1" 404 Not Found
sdx-controller-sdx-controller-1  | INFO:     104.59.236.164:62067 - "GET /SDX-Controller/1.0.0/connection/285eea4b-1e86-4d54-bd75-f14b8cb4a63a HTTP/1.1" 404 Not Found
```
