### ISSUE TITLE
endpoints returns vlan_range instead of vlan

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-controller#333]
GET /l2vpn/1.0 list all connections and  GET /l2vpn/1.0/service_id find a connection returns vlan_range instead of vlan in the JSON response

**Comment by mahidhar1g** [comment]
<img width="1297" alt="Screenshot 2024-10-16 at 9 46 53 AM" src="https://github.com/user-attachments/assets/04a485e4-394d-48a6-b3a5-6d4f8b6dd04f">
HI @congwang09, this is the screenshot from the swagger, it is returning vlan_range

NOTE: While making a post request, I am using this structure (I am using "vlan")

`{
    "name": "fabrictest1",
    "endpoints": [
        {
            "id": "urn:sdx:port:ampath.net:Novi03:1",
            "name": "urn:sdx:port:ampath.net:Novi03:1",
            "vlan": "100"
        },
        {
            "id": "urn:sdx:port:tenet.ac.za:Novi07:1",
            "name": "urn:sdx:port:tenet.ac.za:Novi07:1",
            "vlan": "100"
        }
    ]
}`
