### ISSUE TITLE
use correct attirbute names in GET all l2vpns and Get single l2vpn endpoint

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-controller#336]
{
  "endpoints": [
    {
      "id": "urn:sdx:port:ampath.net:Novi03:1",
      "name": "urn:sdx:port:ampath.net:Novi03:1",
      "vlan": "101"
    },
    {
      "id": "urn:sdx:port:tenet.ac.za:Novi07:1",
      "name": "urn:sdx:port:tenet.ac.za:Novi07:1",
      "vlan": "101"
    }
  ],
  "id": "cc8fe62d-4cb1-4935-a521-6f9830f608bd",
  "name": "fabrictest1"
}

"id" should be service_id.   and id in endpoints object should be port_id.  name is not present in the reposne according to the specification

**Comment by YufengXin** [comment]
(it was from an old branch) current branch returns "service_id" and the name attribute is in the spec:

here is an example of the get L2vpn returned data: https://docs.google.com/document/d/1YKIvNgOaoSA30coT0hvhjVGb8KSu5bNxz3fbfdOBdUY/edit?tab=t.0#bookmark=id.x7yg53g944q2

**Comment by YufengXin** [comment]
This can be closed. The endpoints attributes will be modified in another issue: #337
