### ISSUE TITLE
Version vs. Timestamp logic/processing at the SDX controller needs to be done

### ISSUE THREAD

**Issue by jab1982** [atlanticwave-sdx/sdx-controller#8]
The current SDX Controller doesn't have a processing/logic of the topology fields version and timestamp. Each reports a different context for the topology update data received. 

https://docs.google.com/document/d/1icTfwYlPG4kAhbxb_JO_Xt-N-x7w90XoDgzjfeQTTo0/edit#

**Comment by YufengXin** [comment]
The implementation was done in data model. needs to call here

**Comment by YufengXin** [comment]
Implemented in datamodel, manager.py
